### ISSUE TITLE
Zeppilin contracts

### ISSUE THREAD

**Issue by chrisciszak** [makoto/blockparty#121]
The documentation says to remove the zeppilin contracts. Yet they seem to be referenced in Conference.sol and InvitationRepository.sol?

**Comment by makoto** [comment]
Ah, what I meant is to remove as npm dependency. I would still use it but directly copied under `contracts/zeppelin`

**Comment by makoto** [comment]
Removed the mention from the doc https://github.com/makoto/blockparty/pull/131
