### ISSUE TITLE
Refactor contract to keep gas price capped and also reduce cost fluctuations

### ISSUE THREAD

**Issue by vietlq** [makoto/blockparty#170]
Some executions are ~140K and some ~170K gas:

* 143K gas: https://etherscan.io/tx/0x484106ac8b27f719776343d6e5e4646e548ce3a17350fbbc46f8e9969f60c266
* 165K gas: https://etherscan.io/tx/0xd07103c83c76ad7fcbda80097de2510370a722eca28a16704b007007bbc14f0d
* 159K gas: https://etherscan.io/tx/0x3591682938b0ffae18f8cf8b7d80de347abaca8cb70c3d64ef12987e6e50d92d

**Comment by makoto** [comment]
Redundant to https://github.com/makoto/blockparty/issues/169

**Comment by vietlq** [comment]
169 is UI issue and 170 is another issue, that involves refactoring `register`
