### ISSUE TITLE
Array index bug in revoke function of GroupAdmin

### ISSUE THREAD

**Issue by nemozqqz** [makoto/blockparty#175]
## Description:
In [GroupAdmin.sol](https://github.com/makoto/blockparty/blob/d2a16d42aba3cc1d88a210f7bca4cd6f1e476964/contracts/GroupAdmin.sol), when owner revokes `oldAdmins` from the `admins` array，each address in `oldAdmins` is compared with address in `admins`. While in the for loop in [line 35](https://github.com/makoto/blockparty/blob/d2a16d42aba3cc1d88a210f7bca4cd6f1e476964/contracts/GroupAdmin.sol#L35), the index of `admins` array, `uint j` is not updated because of the typo `++i`, and it should be `++j`. 

```
    function revoke(address[] oldAdmins) public onlyOwner{
        for(uint i = 0; i < oldAdmins.length; i++){
            for (uint j = 0; j < admins.length; ++i) { // typo here!
                if (admins[j] == oldAdmins[i]) {
                    admins[j] = admins[admins.length - 1];
                    admins.length--;
                    emit AdminRevoked(oldAdmins[i]);
                    break;
                }
            }
        }
}
```
## Impact:
This bug will make the call of `revoke` fail and some oldAdmins won't be revoked.
Without `++j`, `j` will always be zero. if `oldAdmins[0] != admins[0]` , the for loop in line 35 won't break, thus variable `i` will eventually execeed the length of `oldAdmins`,  cause array out-of-bound and finally revert the evm state.  
`revoke` function was added since commit [8e94db42](https://github.com/makoto/blockparty/commit/8e94db421e4800d58589a9f04c993ea2d175a8e8)

## Fix:
`` for (uint j = 0; j < admins.length; ++j) ``

**Comment by vietlq** [comment]
Also another tip: Instead of i & j, write better names like `oldAdmIdx` and `newAdmIdx`. Much harder to confuse `old`/`new` compared to `i`/`j`.
