### ISSUE TITLE
Use `constant` for non state changing functions

### ISSUE THREAD

**Issue by makoto** [makoto/blockparty#19]
Instead of

```
function get() returns(uint r) { return info; }
```

do

```
function get() constant returns(uint r) { return info; }
```

This way, the function does not incur transaction gas when called via RPC (or use `internal` keyword if intended to be used only internally).

http://solidity.readthedocs.io/en/latest/contracts.html?highlight=constant#constants

**Comment by jefflau** [comment]
Oh this is interesting. So that's how it knows it's not modifying state?

**Comment by makoto** [comment]
https://github.com/makoto/blockparty/pull/37
